"""
Guess the Number Game.

A console-based game where the player guesses a randomly generated number
within a user-defined range. The game provides hints and temperature feedback.
"""


import random
import time
import sys


# ======================================================================================
# 1. AUXILIARY FUNCTIONS
# ======================================================================================


def greet():
    """
    Display welcome message and game rules.

    Shows a formatted welcome screen with emojis and explains the goal
    of the game. Includes short pauses for better user experience.
    """
    print("\n" + "=" * 50)
    print("🖐️ Welcome to the game 'Guess the number'!")
    print("=" * 50)

    time.sleep(1)
    print("🎯 Your goal is to guess the number generated by the program I wrote.")

    time.sleep(1.5)
    print("🔢 Now, set the starting and ending values to define the range.")

    time.sleep(1.5)


def get_number(prompt):
    """
    Get a valid integer from the user.

    Continuously prompts the user until a valid integer is entered.
    Handles ValueError exceptions and displays an error message.
    """
    while True:
        try:
            return int(input(prompt))
        except ValueError:
            print("❌ Please enter a NUMBER!")


def get_range():
    """
    Get a valid range from the user.

    Prompts for start and end values, validates them and generates
    a random secret number within the range.
    """
    while True:
        start_user_step = get_number("🖥️ Please enter any number for start step: ")

        end_user_step = get_number("🖥️ Please enter any number for end step: ")

        # Easter meme egg: 6-7 joke
        if start_user_step == 6 and end_user_step == 7:
            print("😄 Six-seven.. Are you kidding? Please let's be serious!")
            continue
        if start_user_step < end_user_step:
            secret_number = random.randint(start_user_step, end_user_step)
            return start_user_step, end_user_step, secret_number

        print("❌ Start must be less than end!")


def check_guess(user_guess, secret_number, start_user_step, end_user_step):
    """
    Validate the user's guess and return a boolean.

    Checks if the guess is within the range, correct, higher of lower.
    """

    # Check if guess is outside the valid range
    if user_guess < start_user_step or user_guess > end_user_step:
        return False, f"🤯 Number must be from {start_user_step} to {end_user_step}"

    # Check if guess is correct
    if user_guess == secret_number:
        return True, f"🎉🏆⭐ CONGRATULATION! You guessed the number {secret_number}!"

    # Provide direction hint
    if user_guess < secret_number:
        return False, f"📈 The number is HIGHER! Try again!"
    else:
        return False, f"📉 The number is LOWER! Try again!"


def get_temperature(secret_number, user_guess, start_user_step, end_user_step):
    """
    Calculate how close the guess is to the secret number.
    """
    distance = abs(user_guess - secret_number)
    max_distance = end_user_step - start_user_step

    percent = (distance / max_distance) * 100

    if percent <= 5:
        return f"🔥 Very hot! You almost guessed it!"
    elif percent <= 15:
        return f"☀️ Hot! You're close!"
    elif percent <= 30:
        return f"🌤️ Warm. Keep up the good work!"
    elif percent <= 60:
        return "🌥️ Cool. You're getting there."
    else:
        return f"❄️ Cold. You're far away."


# ===================================================================================
# 2. GAME LOGIC FUNCTIONS
# ===================================================================================


def play_game():
    """
    Run a single game session.

    Handles the main game loop: range setup, guessing, attempt tracking,
    and providing feedback. The game continues until the player guesses
    the secret number.
    """

    start_user_step, end_user_step, secret_number = get_range()
    attempts = 0

    print(f"🤔 I guessed from {start_user_step} to {end_user_step}!")

    while True:
        user_guess = get_number("📝 Your guess: ")
        is_correct, message = check_guess(user_guess, secret_number, start_user_step, end_user_step)

        # Handle out-of-range guesses without counting attempts
        if message == f"🤯 Number must be from {start_user_step} to {end_user_step}!":
            print(message)
            continue

        attempts += 1

        if is_correct:
            print(message)
            print(f"📊 Your Attempts: {attempts}")
            break

        temp = get_temperature(secret_number, user_guess, start_user_step, end_user_step)
        print(message)
        print(temp)


def play_again():
    """
    Ask the player if they want to play again.
    """
    user_answer = input("🎮 Do you want to play again? (y/n): ").lower()
    return user_answer in ['yes', 'y', 'да', 'д']


# ===============================================================================================
# 3. MAIN FUNC
# ===============================================================================================


def main():
    """
    Main game controller.

    Greets the player and runs the game loop. After each game,
    asks if the player wants to play again.
    """
    greet()

    while True:
        play_game()

        if not play_again():
            print(f"Thank you for playing. Goodbye! 👋")
            break

