import random
import time
import sys


# --- 1. AUXILIARY FUNCTIONS ---


def greet():
    # Welcome func with rules and objective
    print("\n" + "=" * 50)
    print("🖐️ Welcome to the game 'Guess the number'!")
    print("=" * 50)

    time.sleep(1)
    print("🎯 Your goal is to guess the number generated by the program I wrote.")

    time.sleep(1.5)
    print("🔢 Now, set the starting and ending values to define the range.")

    time.sleep(1.5)


def get_number(prompt):
    # Number validation func
    while True:
        try:
            return int(input(prompt))
        except ValueError:
            print("❌ Please enter a NUMBER!")


def get_range():
    # Range selection func
    while True:
        start_user_step = get_number("🖥️ Please enter any number for start step: ")
        end_user_step = get_number("🖥️ Please enter any number for end step: ")
        if start_user_step == 6 and end_user_step == 7:
            print("😄 Six-seven.. Are you kidding? Please let's be serious!")
            continue
        if start_user_step < end_user_step:
            secret_number = random.randint(start_user_step, end_user_step)
            return start_user_step, end_user_step, secret_number
        print("❌ Start must be less than end!")


def check_guess(user_guess, secret_number, start_user_step, end_user_step):
    # Response validation func
    if user_guess < start_user_step or user_guess > end_user_step:
        return False, f"🤯 Number must be from {start_user_step} to {end_user_step}"
    if user_guess == secret_number:
        return True, f"🎉🏆⭐ CONGRATULATION! You guessed the number {secret_number}!"
    elif user_guess < secret_number:
        return False, f"📈 The number is HIGHER! Try again!"
    else:
        return False, f"📉 The number is LOWER! Try again!"


def get_temperature(secret_number, user_guess, start_user_step, end_user_step):
    # 'Hot/Cold' calculation func
    distance = abs(user_guess - secret_number)
    max_distance = end_user_step - start_user_step

    percent = (distance / max_distance) * 100

    if percent <= 10:
        return f"🔥 Very hot! You almost guessed it!"
    elif percent <= 30:
        return f"🔥 Hot! You're close!"
    elif percent <= 60:
        return f"🌤️ Warm. Keep up the good work!"
    else:
        return f"❄️ Cold. You're far away."


def compare_with_previous(prev_diff, current_diff):
    pass


# --- 2. GAME LOGIC FUNCTIONS ---


def play_game():
    # Core game func
    start_user_step, end_user_step, secret_number = get_range()
    attempts = 0

    print(f"🤔 I guessed from {start_user_step} to {end_user_step}!")

    while True:
        user_guess = get_number("📝 Your guess: ")
        is_correct, message = check_guess(user_guess, secret_number, start_user_step, end_user_step)

        temp = get_temperature(secret_number, user_guess, start_user_step, end_user_step)

        if message == f"🤯 Number must be from {start_user_step} to {end_user_step}!":
            print(message)
            continue

        attempts += 1
        print(message)
        print(temp)

        if is_correct:
            print(f"📊 Your Attempts: {attempts}")
            break


def play_again():
    # Restart game func
    user_answer = input("🎮 Do you want to play again? (y/n): ").lower()
    return user_answer in ['yes', 'y', 'да', 'д']


# --- 3. MAIN FUNC ---


def main():
    # Main func
    greet()
    while True:
        play_game()
        if not play_again():
            print(f"Thank you for playing. Goodbye! 👋")
            break


# --- 4. ENTRY POINT ---

if __name__ == "__main__":
    main()
